repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace   # Usuwa spacje na końcach linii
      - id: end-of-file-fixer     # Upewnia się, że plik kończy się pustą linią
      - id: check-yaml            # Sprawdza czy pliki .yaml są poprawne
      - id: check-added-large-files # Blokuje commity z wielkimi plikami (np. baza danych)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Użyj 'pre-commit autoupdate' aby pobrać najnowszą wersję
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
