# Generated by Django 6.0.1 on 2026-01-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_bio_user_birth_date_user_first_name_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender_preference",
            field=models.CharField(
                choices=[("M", "Mężczyzna"), ("F", "Kobieta"), ("A", "Dowolna")],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="max_preferred_age",
            field=models.PositiveSmallIntegerField(blank=True, help_text="Maksymalny wiek partnera", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="min_preferred_age",
            field=models.PositiveSmallIntegerField(blank=True, help_text="Minimalny wiek partnera", null=True),
        ),
    ]
