name: Code Quality

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "master"]

jobs:
  backend-quality:
    name: Backend (Django & Ruff)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ruff
        run: pip install ruff

      - name: Fix Ruff issues
        run: ruff check --fix ./backend

      - name: Run Ruff
        run: ruff check ./backend --output-format=github

      - name: Check Code Formatting
        run: ruff format --check ./backend

  frontend-quality:
    name: Frontend (Angular)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Verify Build
        working-directory: ./frontend
        run: npm run build -- --configuration=production
